id: PE6F381C3
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6140
  title: མངོན་པ་གོང་མ་དང་འབྲེལ་བའི་སེམས་ཁམས་རིག་པའི་གཞུང་ལུགས།
  volumes:
    a3fa5de17ea34a08b0a8820ff8ba335c:
      image_group_id: I1KG6207
      title: ''
      base_file: v001.txt
  author: ''
